services:
  node:
    image: node:23 # Official Node.js image
    container_name: react_dev
    working_dir: /app
    environment:
      # make CRA/webpack see changes from host
      CHOKIDAR_USEPOLLING: "true"
      CHOKIDAR_INTERVAL: "200"
      WATCHPACK_POLLING: "true"
      # fix dev websocket port when proxied through Docker
      WDS_SOCKET_PORT: "0"
      # (optional) faster source map generation
      # GENERATE_SOURCEMAP: "false"
    volumes:
      - .:/app
    ports:
      - "3000:3000" # React dev server port
    stdin_open: true
    tty: true
