services:
  node:
    image: node:23 # Official Node.js image
    container_name: react_dev
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "3000:3000" # React dev server port
    stdin_open: true
    tty: true
